### ISSUE TITLE
Scaling issue on my laptop, but not my desktop

### ISSUE THREAD

**Issue by Zilarrezko** [serge-rgb/milton#10]
I was disappointed when I got onto my laptop with my wacom tablet to notice that pen was off from the cursor, and it didn't happen when on my desktop. But I noticed it drew closer to the cursor towards the top left (where I'm assuming the origin is), and got further from the cursor as I drew towards the bottom right. I'll record a video when I get back home and post it here if I remember. (I'm using 1.2.4)

**Comment by serge-rgb** [comment]
Thanks for reporting.
I could replicate this on my desktop by setting the Windows scaling to something greater than 100%. It's a bug in the Wacom event handling.

**Comment by Zilarrezko** [comment]
Ah, well good luck on your development!

**Comment by serge-rgb** [comment]
Thanks! :)

**Comment by jamesnhan** [comment]
Zilarrezko, in case you're having issues with the scaling still, this is how I (kind of, temporarily) fixed it:

> Hey, no sweat. I'm working around the scaling issue by marking Milton to not scale.
> 
> Steps as follows for other users:
> 
> 1. Right-click Milton's shortcut (right-click Milton in the context menu if need be).
> 2. Open Properties.
> 3. Open Compatibility Tab
> 4. Check "Disable display scaling on high DPI settings.
> 
> For screens like my 4K screen, the UI scaling will be almost unreadable, but there's not much you need the UI for if you use the hotkeys like me.

**Comment by Zilarrezko** [comment]
Will do!
