### ISSUE TITLE
Minor comments from Linux packaging

### ISSUE THREAD

**Issue by jonhoo** [serge-rgb/milton#106]
I just wrote up an [Arch Linux package](https://aur.archlinux.org/packages/milton-git) for Milton, and it seems to work! You can see the build script [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=milton-git). The only modifications I had to make it work was to [patch out](https://aur.archlinux.org/cgit/aur.git/tree/no-main.patch?h=milton-git) the `#include` of `platform_main_unix.cc` (which does not exist) and [fix up](https://aur.archlinux.org/cgit/aur.git/tree/carlito-sys.patch?h=milton-git) the path to `Carlito.ttf` so that it wasn't necessary for that file to be in the same directory as the Milton binary. There's even a [Desktop Entry file](https://aur.archlinux.org/cgit/aur.git/tree/milton.desktop?h=milton-git)!

I know Linux isn't official supported at the moment, but figured you (or others) might still find these observations useful. The program otherwise seems to work fine!

**Comment by serge-rgb** [comment]
Hey, thanks for doing this!
