### ISSUE TITLE
Line bug in latest master

### ISSUE THREAD

**Issue by Apostolique** [serge-rgb/milton#107]
https://gfycat.com/SoggyDesertedDingo

I'm getting a bug when I draw a line. Instead of getting a line, I get a sort of curving stroke that is divided in many parts.

This is hard to explain, so I hope you can understand from the video.

The bug was introduced in 777ee42b26de875d69c822254a77e87348d843f3

Specifically, this line is where the lines are broken: https://github.com/serge-rgb/milton/blob/777ee42b26de875d69c822254a77e87348d843f3/src/stroke_raster.f.glsl#L33

**Comment by serge-rgb** [comment]
Thanks for the heads up!
