### ISSUE TITLE
Zoom-out toggle

### ISSUE THREAD

**Issue by serge-rgb** [serge-rgb/milton#109]
Have a key that makes milton zoom out by a fixed amount while it's pressed. This can be used for navigation or to get an overview of the current drawing.

**Comment by Apostolique** [comment]
Along with that, have a key that resets the zoom back to 1.00.

**Comment by serge-rgb** [comment]
Implemented the Peek-out feature.

@Apostolique Maybe create a separate issue for that? I would have to see more people want that though. There's really nothing special about the 1.0 scale, other than it corresponds to the default starting scale.
