### ISSUE TITLE
Blank white window, CPU core pegged

### ISSUE THREAD

**Issue by akbyrd** [serge-rgb/milton#110]
Just tried to install Milton on my PC and it opens to a blank, white window. It chews up about 15% usage and appears to be stuck in a loop. I have to kill it from the Task Manager. I tried 1.6.0 installed and standalone, 1.5.1 standalone, and 1.5.0 standalone. All have the same result. Looks like it may be stalled in `ImGUI setup` according to the log file.

[milton.log](https://github.com/serge-rgb/milton/files/2974760/milton.log)

**Comment by akbyrd** [comment]
Looks like the sdl_event_loop is getting hammered with SDL_SYSWMEVENT. Doesn't seem to ever make it out of the loop. This is the tablet I'm using: https://www.amazon.com/gp/product/B07BF9GNFD/

**Comment by serge-rgb** [comment]
Hey, thanks for the in-depth investigation.
