### ISSUE TITLE
Brush cursor issue

### ISSUE THREAD

**Issue by terrybrashaw** [serge-rgb/milton#12]
The cursor for the brush tool seems to be messed up.

![Cursor](http://i.imgur.com/CcgxBRA.png)

Video here: https://www.youtube.com/watch?v=yiicPR_D920

This is on Windows 8.1 x64, using [Milton 1.2.5](https://github.com/serge-rgb/milton/releases/tag/v1.2.5).

(Also, unrelated: if you'll notice in the video, Milton is missing its icon in the title bar.)

**Comment by serge-rgb** [comment]
It's not messed up, my "design" is just really ugly :) 
But it's been bothering me too. I'll add it to the list.

Also, the installer was not copying the icon file to the install directory. 

Thanks for the reports!

**Comment by brashaw** [comment]
The black/white circle you used as a cursor in [Milton 1.1.0](https://www.youtube.com/watch?v=g27gHio2Ohk) looked perfect, I think.

**Comment by serge-rgb** [comment]
There are two cursors, one is drawn at the current brush size unless the brush size is smaller than a certain threshold, in which case it gets hidden. The other is the system cursor, which on Windows is forced to be of size 32x32. I believe the system cursor can be set to a different size with Direct3D, but OpenGL does not have equivalent functionality AFAIK.

It's not pretty to have two cursors, but it feels so much better to have the system cursor, since it bypasses the compositor. You can see in your video how the "software" cursor lags behind the system cursor. The effect on perceived latency is significant enough to be worth it IMO.

**Comment by brashaw** [comment]
To be more precise, I think a simple black/white circle would make a better system cursor for the brush than the current one.  Something like this (but not as thick): 
![Cursor](http://i.imgur.com/P4xfMBI.png)

I haven't tried, but it looks like you can bypass the 32x32 system cursor size limit by using [SetSystemCursor](https://msdn.microsoft.com/en-us/library/windows/desktop/ms648395(v=vs.85).aspx) mentioned [here](http://stackoverflow.com/questions/13688159/how-to-override-maximum-32x32-mouse-size-in-windows-like-this-program-can).  Then you could have a system cursor that matches the brush size which would be *really* nice.

I would guess that's how [Photoshop bypasses the system cursor size limit](https://www.youtube.com/watch?v=5DWu2HOTteQ).

**Comment by serge-rgb** [comment]
I agree that a circular cursor will work better. 

I remember trying and failing to use SetSystemCursor to get around the 32x32 limit. I wish I remember why I failed! It would be really nice to have one cursor, though. It merits another shot.

**Comment by brashaw** [comment]
Leaving a note here to further confirm that it is possible to bypass the 32x32 limit.

I'm using [LoadImageW](https://msdn.microsoft.com/en-us/library/windows/desktop/ms648045(v=vs.85).aspx) to load cursors like so:

```C
// I don't program in C so take this as pseudo-code.
HCURSOR cursor = (HCURSOR)LoadImageW(NULL, "cursor.cur", IMAGE_CURSOR, 256, 256, LR_DEFAULTCOLOR | LR_SHARED | LR_LOADFROMFILE);
```

Then doing the standard [SetCursor](https://msdn.microsoft.com/en-us/library/windows/desktop/ms648393(v=vs.85).aspx) on `WM_SETCURSOR` messages. This correctly gives me a scaled 256x256 cursor.

I know you generate the cursor for Milton at runtime but maybe this'll help.

Good luck. :)

**Comment by serge-rgb** [comment]
Thanks! Leaving this issue open until I switch the double cursor for SetCursor on Windows :)

**Comment by serge-rgb** [comment]
Closing this issue. The new HW cursor is prettier/less ugly. Also, there is a lot less latency in the newer builds and it might be reasonable to get rid of the HW cursor
