### ISSUE TITLE
Can't start v.1.6 - missing dll file

### ISSUE THREAD

**Issue by bigov** [serge-rgb/milton#120]
Can't start Milton on the MS-Windows - 7pro (x64). And .zip archive and .exe installer have this problem:

![image](https://user-images.githubusercontent.com/9497199/56561930-356f9f00-65e3-11e9-8c1b-7beab23a6eeb.png)

missing file "api-ms-win-core-libraryloader-l1-2-0.dll" or "api-ms-win-core-libraryloader-l1-2-1.dll"

**Comment by serge-rgb** [comment]
I'm aware of this problem! Fixing for 1.6.1
