### ISSUE TITLE
Possible false positive on setup file?

### ISSUE THREAD

**Issue by Some-T** [serge-rgb/milton#128]
https://www.virustotal.com/gui/file/8bdd39b3c39231effeecb3a66d61638b1cae2b37f515613afc897d031c2befd2/detection

**Comment by serge-rgb** [comment]
Yeah... I've had these kinds of problems before. I don't think there's a lot that can be done? :/

**Comment by Some-T** [comment]
I think you have to contact each virus company separately to inform them its a false positive then they take it off there hit list so to speak. If it's not an actual virus then I will not worry about it. Closing issue. Thanks for responding.
