### ISSUE TITLE
Scaling Issue

### ISSUE THREAD

**Issue by jamesnhan** [serge-rgb/milton#13]
When scaling the display on Windows for high DPI screens (e.g. 4K screens), the canvas acts as if the screen is not scaled, so the touch location does not correlate with where the marks are made on the canvas.

Edit: I see a duplicate issue, and that the developer is aware.

**Comment by serge-rgb** [comment]
Yes, I'm aware of the issue. Sorry that I haven't gotten around to fixing it yet! I'll fix this for the next release, which is taking a while because I'm rewriting the renderer. Thanks for your patience!

**Comment by jamesnhan** [comment]
Hey, no sweat. I'm working around the scaling issue by marking Milton to not scale.

Steps as follows for other users:

1. Right-click Milton's shortcut (right-click Milton in the context menu if need be).
2. Open Properties.
3. Open Compatibility Tab
4. Check "Disable display scaling on high DPI settings.

For screens like my 4K screen, the UI scaling will be almost unreadable, but there's not much you need the UI for if you use the hotkeys like me.

**Comment by alexanderbock** [comment]
Update for this:

Doing this on commit 301fbc2410d8288cd426b3ee29548318a636b862 throws an assertion in
`sdl_milton.cc` line 711 

Hotfix: Commenting out the `INVALID_CODE_PATH` "fixes" the issue and it is doable again
