### ISSUE TITLE
[SPACE] for moving the canvas doesn't work.

### ISSUE THREAD

**Issue by aameen951** [serge-rgb/milton#132]
I'm not using a drawing board and the only way I found to move around the board is to go to the menu, select `move canvas`, drag the mouse one time, go to the menu again, select `move canvas`, drag the mouse one time, ...

However, the menu is indicating that `[SPACE]` is the key binding for moving the canvas but it doesn't work.

Also, I think panning should be a separate mode that persists rather than a single-drag thing and once the user select it he has to select the brush again before he can start drawing.

Or maybe making panning mode active as long as the user is holding `[SPACE]` down.

**Comment by Apostolique** [comment]
Space + Drag works for me on the latest version. Are you using a special keyboard?

**Comment by aameen951** [comment]
I'm using version `1.6.2` and it doesn't work.

**Comment by aameen951** [comment]
Oops, the problem was because I'm using the touchpad. I'm double-tapping, holding then dragging. This has always worked for me as drag in all application. But it didn't work in Milton. I'll look at the code and try to figure out why.

If it turns out to be a touchpad problem I'll close this issue. otherwise, if there is something that can be done, I'll propose the changes here.

**Comment by aameen951** [comment]
It turns out the problem is the touchpad driver or Windows. When you press and hold a key (in this case space) the touchpad behave in a weird way and the double-click drag doesn't send the expected events to the window. Milton has nothing to do with the problem and I'm closing this issue.
