### ISSUE TITLE
Undefined reference (Mac)

### ISSUE THREAD

**Issue by UndeRus** [serge-rgb/milton#149]
Missing function
`YesNoCancelAnswer platform_dialog_yesnocancel(char* info, char* title)`
in file src/platform_mac.mm which needed to linking binary during macos build

**Comment by etscrivner** [comment]
Adding this to `src/platform_mac.mm` allowed me to compile and run:

```
YesNoCancelAnswer
platform_dialog_yesnocancel(char* info, char* title)
{
    @autoreleasepool {
        NSAlert *alert = mac_alert(info, title);
        [alert addButtonWithTitle:NSLocalizedString(@"Yes", nil)];
        [alert addButtonWithTitle:NSLocalizedString(@"No", nil)];
        [alert addButtonWithTitle:NSLocalizedString(@"Cancel", nil)];
        NSModalResponse result = [alert runModal];
        if (result == NSAlertFirstButtonReturn) {
          #undef YES
          return YesNoCancelAnswer::YES;
        }
        else if (result == NSAlertSecondButtonReturn) {
          #undef NO
          return YesNoCancelAnswer::NO;
        }
        return YesNoCancelAnswer::CANCEL;
    }
}
```

**Comment by serge-rgb** [comment]
I'd be fine with renaming YES and NO to YES_ and NO_ with a comment explaining why. And I'd be interested in a PR if you want to merge in your changes! Otherwise I will hopefully get to it eventually

**Comment by etscrivner** [comment]
@serge-rgb Done! I've renamed the constants and added an explanatory note in source code. I've also added the function `platform_dialog_yesnocancel` for macOS.
