### ISSUE TITLE
build with errors

### ISSUE THREAD

**Issue by svsdval** [serge-rgb/milton#150]
here is log:
[build.log](https://github.com/serge-rgb/milton/files/3670018/build.log)
seems COUNT is reserved, and extra semicolon on "platform_dialog_yesnocancel(char* info, char* title);"

i fixed problems and get problems with linking
[build_link.log](https://github.com/serge-rgb/milton/files/3670193/build_link.log)

and gcc version:
[gcc_version.log](https://github.com/serge-rgb/milton/files/3670037/gcc_version.log)

**Comment by danfe** [comment]
`COUNT` is not really _reserved_, there is a conflict with macro definition on the same name in the `X11/extensions/XI.h`, it can be worked around by `#undef`ing it inside that `enum`.

Stray semicolon is indeed a bug and should be removed.

**Comment by svsdval** [comment]
yup, undefining COUNT in enum and removing the extra semicolon was helped but still have error while the linking.

[linking.log](https://github.com/serge-rgb/milton/files/3671432/linking.log)

**Comment by danfe** [comment]
Please see how to fix those missing symbols in  #148.

**Comment by svsdval** [comment]
Thanks, this solved missing symbols =). Who should close the issue ?

**Comment by danfe** [comment]
I'd rather prefer that the author committed the necessary changes and closed this himself.  Otherwise people will come and keep opening identical bugs again and again.  Until the problem properly fixed (in the repository), it's better to keep this issue open for other's benefit.

**Comment by svsdval** [comment]
ok =) Thanks

**Comment by serge-rgb** [comment]
Thanks to @chipviled for the PR and to the people helping out here!
