### ISSUE TITLE
All Monitors Mapped / Display Tablet Drawing Incorrectly

### ISSUE THREAD

**Issue by AverageTrailerTrash** [serge-rgb/milton#161]
The program works fine when I use my mouse, but if I try to use the stylus of my Ugee display monitor, what I draw is to the left of the cursor on my rightmost monitor, to the right of the cursor on my leftmost monitor... This only occurs while pressing the pen down and drawing on the canvas -- I can click through the menus and whatnot without any problems.

There is a similar issue with this tablet in Clip Studio Paint if the "Set tablet operation area with application" setting is enabled instead of "Use mouse mode in setting of tablet driver," in case that information might help. 

This tablet always maps to one full monitor at a time and can't be set to use a smaller portion of the screen or all screens at once in its driver, so the hack mentioned in #94 doesn't help.

Everything else about my tablet works fine in this program (eraser toggle, pen pressure, etc). It's just the position of what's drawn. 

I'm on Windows 8.1 x64. This occurs with or without digital ink enabled in my tablet driver. (In addition, after using the stylus, the mouse doesn't draw at all until I re-open the program. This also occurs in CSP when using the settings mentioned, so I assume they're part of the same issue.)

![MiltonPaint](https://user-images.githubusercontent.com/13239938/75768527-83c8f080-5d12-11ea-80e1-5867b9404d3d.gif)

**Comment by AverageTrailerTrash** [comment]
This appears to have been a driver issue of some kind on my end. I tried installing my old Wacom tablet & it worked fine. After removing it and reinstalling my usual Ugee tablet, the program worked correctly with it as well. AFAIK the original driver was up to date, so I'm not sure what went wrong. But at least it works now.

**Comment by serge-rgb** [comment]
Thanks for getting back on this! I'm glad that it's working now

**Comment by vladh** [comment]
I have the exact same problem on Windows 10. It doesn't happen in Paint or other drawing applications. I'm forced to use pen as opposed to mouse mapping if I want to use Milton. :(
