### ISSUE TITLE
[UNRESOLVED] Windows version crashing at startup 

### ISSUE THREAD

**Issue by githubuser181226** [serge-rgb/milton#178]
Milton keeps crashing on me at startup, every time
Getting

> Warning: Failed to read settings file

and

> milton_load: Could not open file!

messages in the log (see below).

I'm using Win7 SP1 x64, GPU is Intel HD3000 (i5-2520m), 16GB RAM

Milton.log

> CommandLine is 
Running Milton 1.9.1 (Release) 
Initializing SDL... Done.
Loading preferences...
Prefs file: C
Could not open file for writing prefs
Window dimensions: 1280x800 
Requesting OpenGL 2.1 context.
Creating Milton Window
Loaded glGetError rom WGL
Loaded glGetAttribLocation rom WGL
Loaded glGetUniformLocation rom WGL
Loaded glGetString rom WGL
Loaded glGetStringi rom WGL
Loaded glBindFramebufferEXT rom WGL
Loaded glBindTexture rom WGL
Loaded glBufferData rom WGL
Loaded glCompileShader rom WGL
Loaded glEnable rom WGL
Loaded glFramebufferTexture2DEXT rom WGL
Loaded glGenFramebuffersEXT rom WGL
Loaded glGenTextures rom WGL
Loaded glAttachShader rom WGL
Loaded glIsProgram rom WGL
Loaded glIsShader rom WGL
Loaded glCreateShader rom WGL
Loaded glGetIntegerv rom WGL
Loaded glGetProgramInfoLog rom WGL
Loaded glGetProgramiv rom WGL
Loaded glGetShaderInfoLog rom WGL
Loaded glGetShaderiv rom WGL
Loaded glLinkProgram rom WGL
Loaded glShaderSource rom WGL
Loaded glTexImage2D rom WGL
Loaded glTexParameteri rom WGL
Loaded glUniform1f rom WGL
Loaded glUniform1i rom WGL
Loaded glUniform2f rom WGL
Loaded glUniform2fv rom WGL
Loaded glUniform2i rom WGL
Loaded glUniform2iv rom WGL
Loaded glUniform3fv rom WGL
Loaded glUniform3iv rom WGL
Loaded glUniform4fv rom WGL
Loaded glUniformMatrix2fv rom WGL
Loaded glUseProgram rom WGL
Loaded glValidateProgram rom WGL
Loaded glCheckFramebufferStatusEXT rom WGL
Loaded glCreateProgram rom WGL
Loaded glBindBuffer rom WGL
Loaded glBindVertexArray rom WGL
Loaded glGenBuffers rom WGL
Loaded glGenVertexArrays rom WGL
Loaded glGetFloatv rom WGL
Loaded glIsEnabled rom WGL
Loaded glActiveTexture rom WGL
Loaded glBlendEquation rom WGL
Loaded glBlendEquationSeparate rom WGL
Loaded glBlendFunc rom WGL
Loaded glBlitFramebufferEXT rom WGL
Loaded glClear rom WGL
Loaded glClearColor rom WGL
Loaded glClearDepth rom WGL
Loaded glCopyTexImage2D rom WGL
Loaded glDeleteBuffers rom WGL
Loaded glDeleteVertexArrays rom WGL
Loaded glDepthFunc rom WGL
Loaded glDisable rom WGL
Loaded glDrawArrays rom WGL
Loaded glDrawElements rom WGL
Loaded glEnableVertexAttribArray rom WGL
Loaded glPixelStorei rom WGL
Loaded glReadPixels rom WGL
Loaded glScissor rom WGL
Loaded glUniformMatrix4fv rom WGL
Loaded glVertexAttribPointer rom WGL
Loaded glViewport rom WGL
Loaded glDetachShader rom WGL
Loaded glDeleteProgram rom WGL
Loaded glDeleteTextures rom WGL
Loaded glDeleteShader rom WGL
Loaded glPolygonMode rom WGL
Created OpenGL context with version 3.1.0 - Build 9.17.10.4229
    and GLSL 1.40 - Intel Build 9.17.10.4229
UI scale is 1.000000
Warning: Failed to read settings file
Setting default view
Maximum viewport dimensions, 8192.000000x8192.000000
Vendor string: "Intel"
Set milton file: C
Loading file C
milton_load: Could not open file!
Increased guid to 1
Setting default view
Set milton file: C
Setting up hardware cursor.
ImGUI setup

**Comment by serge-rgb** [comment]
Thanks for the report.

The two "Could not open file!" and "Failed to read settings file" are harmless errors. They just occur when Milton starts for the first time on a clean install. 

From the log file I would assume it's crashing somewhere in the ImGUI loading code. I can't really debug this without a repro :(

**Comment by githubuser181226** [comment]
I don't know either. the window shows up for a split second (no controls just a frame) than the process terminates leaving only this log file and I see no trace in the event viewer. 
I tested on another computer with i3 and intel 520, and it works, but also that's a clean install, so in the end I have no idea what's wrong with my current set up.
all the drivers are up to date, msvc libraries installed (2008-2019), I don't know what the other system requirements are.
this is weak :(

**Comment by Pale-Gray** [comment]
this happens to me also.
