### ISSUE TITLE
build issue: error C2732: linkage specification contradicts earlier specification for 'win32_log'

### ISSUE THREAD

**Issue by shohidulhaque2** [serge-rgb/milton#199]
When building milton using 'x64 Native Tools Command Prompt for VS 2019' on Windows, 10 I get the following build error:

C:\Users\jj\Documents\workspace\development\milton>build.bat
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30145 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

shadergen.cc
Microsoft (R) Incremental Linker Version 14.29.30145.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:shadergen.exe
/debug
shadergen.obj
ERROR: The process "milton.exe" not found.
Generating shader code...
Shaders generated OK
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
Copyright (C) Microsoft Corporation.  All rights reserved.

Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30145 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

unity.cc
C:\Users\jj\Documents\workspace\development\milton\src\platform_windows.cc(372): error C2732: linkage specification contradicts earlier specification for 'win32_log'
C:\Users\jj\Documents\workspace\development\milton\src\platform_windows.cc(371): note: see declaration of 'win32_log'
C:\Users\jj\Documents\workspace\development\milton\src\platform_windows.cc(383): error C2732: linkage specification contradicts earlier specification for 'win32_log_args'
C:\Users\jj\Documents\workspace\development\milton\src\platform_windows.cc(382): note: see declaration of 'win32_log_args'

**Comment by serge-rgb** [comment]
Should be fixed with 9aeaffd76f4!
