### ISSUE TITLE
Crash when compiling shaders

### ISSUE THREAD

**Issue by warmist** [serge-rgb/milton#22]
Milton crashes (using 1.2.6 x64 win portable) with following error:
`Vertex shader failed to compile with the following errors:
ERROR: error(#271) Explicit version number 120 not supported by GL3 forward compatible context`

My graphics is: AMD Radeon R9 200 Series

**Comment by warmist** [comment]
Also tried 1.2.5
Same thing.

**Comment by serge-rgb** [comment]
This is already fixed in master. A new release is coming soon.
Thanks for reporting!
