### ISSUE TITLE
Middle-mouse panning issue

### ISSUE THREAD

**Issue by terrybrashaw** [serge-rgb/milton#25]
**Milton:** 1.2.7
**OS:** Windows 8.1

After panning with middle-mouse, the cursor gets stuck in a panning/brush state.

Video: https://www.youtube.com/watch?v=U8E01fJk0yU

You'll notice that after panning, the cursor flickers between the brush and panning. You can get out of this state by clicking a few times.

**Comment by serge-rgb** [comment]
Thanks for reporting. I can replicate this on my machine.
