### ISSUE TITLE
Panning only works ~50% of times

### ISSUE THREAD

**Issue by netwerkz** [serge-rgb/milton#31]
Using the mouse to middle click and drag to pan, I find myself trying to pan several times extra, because it skips panning a lot of times.
Otherwise it's a very good piece of software, kudos @serge-rgb. You do a great job! Thanks

**Comment by serge-rgb** [comment]
Thanks for reporting!
I could replicate this in 1.2.7 but it seems to have been accidentally fixed in the development branch.
