### ISSUE TITLE
Panning broke in 1.2.8 and 1.3.0

### ISSUE THREAD

**Issue by Apostolique** [serge-rgb/milton#41]
When I use the middle click button on my mouse, I can pan.

On my Wacom bamboo tablet, the button is set be a middle click. It doesn't pan.

Oddly enough, if I go in my Wacom settings, change the button to something else, then set it back to middle mouse button, the panning works for a single time. After that it stops working again. Hopefully that helps.

Edit: Tested to make sure, the panning works on version 1.2.7.
Edit2: Pressing space bar and dragging does work even with the pen.

**Comment by serge-rgb** [comment]
Thanks! I probably introduced the bug when I was messing with the Wacom button code.

**Comment by serge-rgb** [comment]
I believe it's fixed. The fixed will be included in version 1.2.9

**Comment by Apostolique** [comment]
Oh cool! Good job!
