### ISSUE TITLE
Zoom info feature request

### ISSUE THREAD

**Issue by Apostolique** [serge-rgb/milton#42]
In a previous version, there was a debug window that showed the zoom level. It looks like the debug window was removed. It would be nice if the zoom level was shown somewhere on the interface (perhaps at the top next to the last save info).

**Comment by serge-rgb** [comment]
You can check out the debug window in milton_configuration.h and the MILTON_ENABLE_PROFILING flag.

But I agree that the interface should inform the user about the current zoom level.

**Comment by serge-rgb** [comment]
This is now in master. Will be in the next release.
