### ISSUE TITLE
Invisible Cursor  in 1.2.8

### ISSUE THREAD

**Issue by quantumv** [serge-rgb/milton#43]
I can't see the circle cursor in 1.2.8. 1.2.7 works fine.

**Comment by serge-rgb** [comment]
I think this should be fixed in the master branch. After the next version comes out, if you still have this problem, please let me know and I will reopen this issue.

**Comment by quantumv** [comment]
I can confirm the issue is fixed in 1.4.0! Thanks a lot!

**Comment by serge-rgb** [comment]
Good to know :) Thanks for the confirmation!
