### ISSUE TITLE
Drawing while erasing 

### ISSUE THREAD

**Issue by sweetcode** [serge-rgb/milton#45]
Version: 1.2.8

Hello, I've found this strange bug that is causing Milton to draw the path of your eraser and recreating the erased part.

1. Keep your mouse button always pressed, never let it go
2. Draw something
3. Select the eraser via hotkey 
4. Erase the things you drawed
5. Select the brush via hotkey
--> It redraws the erased part as well as the path of the eraser

Here is a short video showing it off: https://www.youtube.com/watch?v=iwcu7blRG78

**Comment by serge-rgb** [comment]
Thanks for reporting! Fixed
