### ISSUE TITLE
Wacom and high DPI monitors

### ISSUE THREAD

**Issue by alexanderbock** [serge-rgb/milton#46]
When using a Wacom tablet (Intuos 3) on Windows 10 with scaling enabled, the cursor location and drawing location do not match up.

Reproduce:
1. In "Display Settings" set "Change the size of text,apps, and other items:" to any other value than 100%
2. Start Milton
3. Draw

When setting it to 100% and restarting Milton, it works. Also using the mouse cursor works with all scaling values

**Comment by serge-rgb** [comment]
Oops. This bug is a regression. It is now fixed in the master branch. Thanks.

 It will still require you to log out and log back in after changing the  display scaling but I don't know if there's much I can do about that.
