### ISSUE TITLE
Milton 1.2.8 crash

### ISSUE THREAD

**Issue by msmshazan** [serge-rgb/milton#47]
Milton 1.2.8 crashes on win 10 64bit.

**Comment by serge-rgb** [comment]
I need more info to help you. 

Can you send me the contents of %appdata%\MiltonPaint\data\milton.log?
What specs does your machine have?

**Comment by msmshazan** [comment]
Here's the log
Running Milton
Initializing SDL... Done.
Loading preferences... Could not open file for writing prefs
Done.
Creating Milton Window
Created OpenGL context with version 3.1.0 - Build 9.17.10.4229
    and GLSL 1.40 - Intel Build 9.17.10.4229
Maximum viewport dimensions, 8192.000000x8192.000000
Vendor string: "Intel"
Increased guid to 1

PC specs:
Intel Pentium B970 @ 2.30 GHz
Ram: 6.00GB
Os: Windows 10 64bit

**Comment by Capital-EX** [comment]
Milton also crashes on my Surface Book using NVidia running Windows 10 64bit.
I don't know if this will help, but VS 2015 says that WinTab throws an `Integer division by zero` error.

This could be an upstream issue :/

**Comment by serge-rgb** [comment]
Div by zero error should be fixed in easy tab, and OpenGL crash-on-startup errors have already been reported. Most of them should be fixed now
