### ISSUE TITLE
Help Wanted: Testing Milton with Wacom clones

### ISSUE THREAD

**Issue by serge-rgb** [serge-rgb/milton#5]
As of right now, there is rudimentary Wacom support through EasyTab. Just pressure information and position. No buttons or eraser. That will come soon.

This functionality has only been tested by me with my Bamboo Pen & Touch Small. A friend of mine reported having problems with his Chinese tablet, which apparently tries to conform to the Wacom API. I do not have access to his device and I am trying to get in contact with him to fix the bug.

If you have a Wacom competitor that works with other software _with existing Wacom drivers_, please let me know if you have problems! If they really Just Work with other software, they should work with Milton.

This issue would directly help sister project [Papaya](https://github.com/ApoorvaJ/Papaya/), since we share our Wacom code.

**Comment by miotatsu** [comment]
Drawing is working well on my Monoprice 22HD with my Linux build. Don't have pressure sensitivity right now but that is not a milton issue, it's a problem with the driver I'm currently using

**Comment by miotatsu** [comment]
I just got confirmation that pressure is working with the driver I am using. I was able to draw with pressure in gimp after changing a setting. I don't have pressure sensitivity in Milton. I don't know whether [the driver I am using](https://github.com/stacksmith/Monoprice_22_linux_kernel_module) conforms to the Wacom API or if it is doing something else.

If the driver for my tablet is doing something different and support for it would be non-trivial, I'll either live without pressure or look into adding support for it myself, but if there would be an easy change to get pressure going for me that would be awesome.

Sometimes I accidentally press the side button and it occasionally causes random lines to get drawn on the screen. I know that by default the pen's side button is being mapped to right click, and playing with right-click in milton I see that it acts the same as left click. I'll probably look into mapping it to space at some point and post here again if I still have issues with it

**Comment by serge-rgb** [comment]
I don't know if fixing EasyTab for your driver would be an easy fix or not. I will let you know if I make progress, but right now I can't think of what could be the problem. The code for EasyTab is similar to what GTK does as far as I remember. QT is similar too, but there aren't that many people doing this. Most projects are on top of QT or GTK and don't have to do it.

As for the pen button mapping problem. I want the right click to open a context menu so it can just be disabled for now. I'll fix it and do a commit&push.

**Comment by GoldbergJarrett** [comment]
I am having an issue with my huion h420. I use my tablet to plan my programs and such. Kind of like Casey Muratori does with handmade hero. I actually started using milton recently because one note was not doing it for me anymore. Unfortunately when I draw there is a slight lag that stops me from completing my motion. For example if im trying to draw the letter "e" the loop part of the e will always get cut off. huion is a cheap clone tablet but it is very good for people like me who use it for planning. Milton and this tablet is the perfect combo.

**Comment by crhallberg** [comment]
I'm also using the Huion H420, but with a different issue. Pressure is working, but I can only draw in the top left corner. Example:

![tablet](https://user-images.githubusercontent.com/451107/33245609-3126fa50-d2d8-11e7-945b-10263cc12ba2.gif)

> First dot is focus with mouse, rest is tablet

It does interact with the tools up there as well. It tracks the cursor properly but draws improperly.

**Comment by GoldbergJarrett** [comment]
Unfortunately I had to ditch Milton. It just doesn't work and I tried
driver, and messing with settings and even third party programs and nothing
worked.

**Comment by serge-rgb** [comment]
@crhallberg Thanks for the gif. If you're able to recompile, you might want to try playing with the InputExtentX, InputExtentY in [lines 1001-4 of EasyTab.h](https://github.com/serge-rgb/milton/blob/master/src/easytab.h#L1003). Trying some hard coded values. I would start with 

``` 
        EasyTab->InputExtentX = [Your monitor's horizontal resolution];
        EasyTab->InputExtentY = [Your monitor's vertical resolution];
```
 and see if that changes anything. Then make it bigger / smaller.
Otherwise I will eventually get one of these and try it out.

**Comment by serge-rgb** [comment]
@GoldbergJarrett And what where you hoping to accomplish by telling me you "had to ditch" Milton? 
I'm more than happy to work on bug reports for Milton. Unfortunately I am just one person, and fixing the Huion H420 is low on the priority list. You're free to try out any other drawing app without bothering me about it

**Comment by GoldbergJarrett** [comment]
My apologies Sergio. I didn't mean to come off so rude. I was at work and I
responded quickly before my break was over. I still use milton. I love it!
Just can't use it with my cheap tablet. I recently won a surface pro 4 i7
luckily so I shouldn't have anymore issues! If I do I'll let you know! I
apologise again for my impatience and rudeness.

**Comment by serge-rgb** [comment]
Apologies on my end too. It was wrong to respond with a knee jerk reaction and I regretted it immediately. Really sorry about that.. :) 

BTW - I expect Milton won't support pressure sensitivity on the surface pro unless Microsoft implemented support for the Wacom API. As far as I know there are people who use it, though there have been some reports of problems with the Intel integrated graphics. Please let me know if you run into problems.

And again, apologies! Won't happen again.

**Comment by GoldbergJarrett** [comment]
Understood completely! The internet can be very toxic! I sure will let you
know if I come across any trouble!

**Comment by crhallberg** [comment]
![nowwhat](https://user-images.githubusercontent.com/451107/33509350-c1e74a64-d6ce-11e7-960c-1232f66c74ed.gif)

Hard-coding my screen resolution works.

> Sorry, it took me a while to get the source compiling.

**Comment by crhallberg** [comment]
The weird thing is the other tablet I used (Wacom) didn't have this problem. So how do we diagnose it?

**Comment by liorda** [comment]
I can't paint anything with Huion 420 graphics tablet. Single clicks are detected on the GUI windows (brushes, layers, ...) via the pen, but not on the canvas.

**Comment by liorda** [comment]
OK, I think I understand what the problem is. `PacketBuffer[i].pkX` and `PacketBuffer[i].pkY` are given already  scaled (output coordinates), so IMHO the calculations in `EasyTab_HandleEvent()` are wrong because they're done in input coordinates. [Wintab specs](http://www.wacomeng.com/windows/docs/Wintab_v140.htm)

**Comment by anssilap** [comment]
I have Huion H640P and was having same issue as @crhallberg . Hardcoded InputExtent values according to resolution fixed the issue, but I had to multiply X by number or active monitors for some reason. I have 2 monitors using 1920x1080, so this worked for me:
`
    EasyTab->InputExtentX = 1920 * 2;
    EasyTab->InputExtentY = 1080;
`

I got the program working, so I didn't pursue proper fix any further.

Awesome program by the way. Compared to most other painting programs Milton feels so responsive. I love my new whiteboard that has practically unlimited size!

**Comment by liorda** [comment]
I forked the project with my proposed change, which works for me. People with a wacom tablet, and/or dual monitors, and/or other kinds of tablets - please test my fork. If it's any good, I'll do a PR. [Link](https://github.com/liorda/milton).

**Comment by anssilap** [comment]
@liorda I tested your fork on my H640P and it works fine with my setup. I tested with two monitors and tried switching primary display in display settings and mapping tablet to a different screen in Huion configuration. As long as I restart Milton after making any changes to these configurations, it seems to work as expected.

Hopefully I'll be able to test this with a Wacom setup later today. That machine has double/triple display with varying display sizes and some rather old Intuos Wacom tablet. Testing with Wacom tablet could give some indication if these changes affect Wacom users in some way.

**Comment by liorda** [comment]
@anssilap interesting, thanks for reporting. I wonder if I should have used the "system" data from the packet instead of the "output", because it works for the Huion either way. Maybe I'll be able to test it on a wacom from work later today.

**Comment by serge-rgb** [comment]
Hey @anssilap and @liorda , thanks for your time!

@liorda , I'm looking at your fork. It looks fine to me, I just have a couple comments:

Instead of flipping coordinates for each packet (line 1107), it's probably better to leave the line `LogContext.lcOutExtY = -LogContext.lcOutExtY;`, which should accomplish the same thing. Am I right? It's been long enough since I touched Wacom code that it's flushed from my brain.

Also, I normally accept PRs and then change the code-style myself, but if you could just align it to four spaces instead of tabs it would be better. No big deal either way.

Anyway, from what I read in the comments it looks like @liorda 's fix works. Thanks a lot everyone!

**Comment by liorda** [comment]
@serge-rgb see @anssilap edit - it didn't work for him on dual screen setup. I just comitted another change. Can you see if it still works for your Wacom? I don't understand how the negation helps. Also changed to spaces.

**Comment by serge-rgb** [comment]
Closing as I get ready for a new release, for which huion tablets should work.
