### ISSUE TITLE
Launch crash - v1.4.0

### ISSUE THREAD

**Issue by n13x** [serge-rgb/milton#52]
This is the first time I am launching the application on this laptop.
It opens the window to the canvas, and then crashes with an error. Windows asks to look for a solution online/close the application.

The log file show this:
```
CommandLine is 
Running Milton
Initializing SDL... Done.
Loading preferences... Could not open file for writing prefs
Done.
Creating Milton Window
Created OpenGL context with version 3.1.0 - Build 8.15.10.2538
    and GLSL 1.40  - Intel Build 8.15.10.2538
Maximum viewport dimensions, 8192.000000x8192.000000
Vendor string: "Intel"
Milton: loading file
Could not open file!Increased guid to 1

```
Machine specs:
```
Windows 7 x64 Professional
Intel i5-2520M
4GB RAM
```

**Comment by serge-rgb** [comment]
Could you try deleting the folder `%appdata%\MiltonPaint`? Maybe it's a weird permission issue? :/

**Comment by n13x** [comment]
I tried deleting the folder, and reinstalling, still the same issue happens.
I took a screenshot of the window when the crash happens.
![error](https://cloud.githubusercontent.com/assets/28954261/26493680/4421ac40-41f1-11e7-90d4-1ce6c78b3f2f.PNG)

**Comment by n13x** [comment]
I found what the issue was.

I have two graphics processors in this laptop, I have to use the second one for Milton. The first one causes the crash.

(Right click > Run with graphics processor > select different card)
