### ISSUE TITLE
Milton 1.4.0 crash on windows 10

### ISSUE THREAD

**Issue by msmshazan** [serge-rgb/milton#53]
Here's the Log:

CommandLine is 
Running Milton
Initializing SDL... Done.
Loading preferences... Could not open file for writing prefs
Done.
Creating Milton Window
Created OpenGL context with version 3.1.0 - Build 9.17.10.4229
    and GLSL 1.40 - Intel Build 9.17.10.4229
Maximum viewport dimensions, 8192.000000x8192.000000
Vendor string: "Intel"
Milton: loading file
Could not open file!Increased guid to 1

**Comment by serge-rgb** [comment]
Maybe this issue is related to #52?  If you have more than one graphics chip, could you please try running Milton specifying one graphics card?
From the issue #52:

> I found what the issue was.
> 
> I have two graphics processors in this laptop, I have to use the second one for Milton. The first one causes the crash.
> 
> (Right click > Run with graphics processor > select different card)

**Comment by msmshazan** [comment]
I have only one graphics card and its the intel integrated GPU.

**Comment by n13x** [comment]
Milton will not work on the Intel integrated GPU. That is why I had the problem, and fixed it by switching to a real GPU.

**Comment by techtide** [comment]
I get the same error on Milton 1.4.4.

**Comment by serge-rgb** [comment]
Closing for now, as the new release will have some GL compat improvements that I think will fix most crash-on-startup problems.
