### ISSUE TITLE
Getting an assertion crash when I launch the program.

### ISSUE THREAD

**Issue by griggsca91** [serge-rgb/milton#60]
Here is the log

CommandLine is 
Running Milton
Initializing SDL... Done.
Loading preferences... Could not open file for writing prefs
Done.
Creating Milton Window
Created OpenGL context with version 4.5.13447 Compatibility Profile Context 16.300.2311.0
    and GLSL 4.50
Maximum viewport dimensions, 16384.000000x16384.000000
Vendor string: "ATI Technologies Inc."
Milton: loading file
Could not open file!Increased guid to 1

[here is a screen shot](http://imgur.com/a/c2eZW)

**Comment by serge-rgb** [comment]
Thanks for the detailed report! I will fix this and push a release in the next couple days.

**Comment by serge-rgb** [comment]
Hey,
I pushed a new release without the "invalid code path"  (v1.4.4)
Your mouse cursor may look weird, but if that happens the log will print out enough info to really fix it.

**Comment by serge-rgb** [comment]
Closing for now, as the new release will have some GL compat improvements that I think will fix most crash-on-startup problems.
