### ISSUE TITLE
Milton 1.5.1 crashes on closing

### ISSUE THREAD

**Issue by elozanoch** [serge-rgb/milton#64]
CommandLine is 
Running Milton
Initializing SDL... Done.
Loading preferences... Could not open file for writing prefs
Done.
Creating Milton Window
Created OpenGL context with version 4.5.0 NVIDIA 385.69
    and GLSL 4.50 NVIDIA
Easy Tab Failed to load. Code -3Maximum viewport dimensions, 16384.000000x16384.000000
Vendor string: "NVIDIA Corporation"
Milton: loading file
Could not open file!Increased guid to 1

**Comment by mcmihai** [comment]
I think it's dereferencing a null pointer in EasyTab_Unload() since it calls it even if it fails to load.

**Comment by serge-rgb** [comment]
That's probably it. Thanks!

**Comment by serge-rgb** [comment]
Closing this issue as it's already fixed in master.
