### ISSUE TITLE
Error on function glStringi

### ISSUE THREAD

**Issue by flamendless** [serge-rgb/milton#74]
Hi, ive downloaded and installed latest version of milton paint on my windows ten laptop. When I open it, says error:
"Could not load function glGetStringi"

**Comment by serge-rgb** [comment]
What gpu does your laptop have? Do you have the latest drivers installed?
If it does, then it might just not support the GL functionality milton needs, so this would be expected behavior. Though there should be a clearer way of informing the user about it.

**Comment by flamendless** [comment]
![cpu-info](https://user-images.githubusercontent.com/17418737/34704610-3da3e16a-f535-11e7-9ffe-60812714af86.gif)

Here's the info

**Comment by serge-rgb** [comment]
This is unfortunately too underpowered for Milton, but instead of crashing it should be outputting useful info, so I'll fix that..
