### ISSUE TITLE
Crashes immediately on launch (Win7x64)

### ISSUE THREAD

**Issue by fadelm0** [serge-rgb/milton#75]
Let me know if/how I can provide any further info to help diagnose it, as I haven't been able to run it for the reason in the title, and I couldn't find any log files.

**Comment by Apostolique** [comment]
Did you try compiling Milton from source?

**Comment by serge-rgb** [comment]
This usually means that your hardware does not support the GL functionality that Milton needs. I'm working on making Milton handle this more gracefully.
Did you look in %APPDATA%\MiltonPaint\data for the log? That's where it normally is.

**Comment by JPBotelho** [comment]
Have the same problem. Here's the log:

`CommandLine is 
Running Milton
Initializing SDL... Done.
Loading preferences... Could not open file for writing prefs
Done.
Creating Milton Window
Created OpenGL context with version 2.1.0 - Build 8.15.10.2622
    and GLSL 1.20  - Intel Build 8.15.10.2622
Easy Tab Failed to load. Code -3Maximum viewport dimensions, 8192.000000x8192.000000
Vendor string: "Intel"
Milton: loading file
Could not open file!Increased guid to 1
`

**Comment by fadelm0** [comment]
Same situation as @JPBotelho here, including similar craptop specs.
This is the log:

> CommandLine is 
> Running Milton
> Initializing SDL... Done.
> Loading preferences... Could not open file for writing prefs
> Done.
> Creating Milton Window
> Created OpenGL context with version 3.1.0 - Build 9.17.10.2963
>     and GLSL 1.40 - Intel Build 9.17.10.2963
> Maximum viewport dimensions, 8192.000000x8192.000000
> Vendor string: "Intel"
> Milton: loading file
> Could not open file!Increased guid to 1

**Comment by serge-rgb** [comment]
Closing this. Milton should now give more detailed info before crashing on startup.
