### ISSUE TITLE
Incorrect behavior with Wacom tablets when using Tablet Area option

### ISSUE THREAD

**Issue by mrim5** [serge-rgb/milton#8]
I sometimes use my Wacom Intuos 4 in a vertical orientation where I have the screen mapped to only a portion of the tablet's working area. A screenshot of how I have the tablet set up is below. 

![aaa](https://cloud.githubusercontent.com/assets/18471485/15523180/9d64d272-21e6-11e6-91e9-1ecdd6e1b0f2.png)
Milton seems to ignore these settings  (i.e., the red rectangle). Instead, it maps the entire working area to the screen, which results in a squashed aspect ratio when the tablet is in a vertical orientation (i.e., I have to move the pen a greater distance vertically than horizontally to move the same distance on screen).

**Comment by serge-rgb** [comment]
Thanks for reporting this!

**Comment by serge-rgb** [comment]
I believe the latest build (v1.2.3) fixes the problem. 
If you are still having trouble, please let me know so I reopen the issue. 
Thanks
