### ISSUE TITLE
Input lag in 1.6.2

### ISSUE THREAD

**Issue by Apostolique** [serge-rgb/milton#81]
In version 1.6.2, I'm getting some input lag when I start a stroke. The lag happens when I draw with both my tablet or my mouse.

I checked version 1.2.8 and there is no input lag.

But input lag, I mean that I press down to start a stroke, then start moving, the stroke will only appear a couple milliseconds later. If during those milliseconds I draw a squiggly line really fast, when the stroke appears, the details aren't lost (The squiggly line exists.). So I'm guessing it has to do with the stroke not getting shown right away, but the inputs still getting processed.

Edit: If I try to do a lot of quick strokes though (faster than the ms delay), none of the lines appear.

**Comment by serge-rgb** [comment]
I remember getting weird lag in the drawing you sent me. Does this happen with a blank canvas as well?

**Comment by Apostolique** [comment]
Oh! You're right, with a new canvas, there is no lag.

**Comment by serge-rgb** [comment]
It must be something that was corrupted in the save that I didn't catch. Don't know what it could be. Anyway. I'm closing this issue since it's a pretty specific problem :)

**Comment by Apostolique** [comment]
Sounds good, I'll just create a new file.
