### ISSUE TITLE
Rebind keyboard shortcuts

### ISSUE THREAD

**Issue by Tahv** [serge-rgb/milton#82]
Hello,

Is it possible to add a way to remap keybards shortcuts. I'm working with an AZERTY keyboards and some of the shortcuts are hardly accessibles or clash with others ("[" for brush size is on the same key as "5" and trigger brush opacity to change)

**Comment by serge-rgb** [comment]
Hey, thanks for this. I have never used the AZERTY keyboard layout, which probably explains why it doesn't make any sense.
I don't think keyboard remapping will make it to the next release, but I added fixing AZERTY to the to-do list.

**Comment by jonhoo** [comment]
I think this is particularly important for drawing tablets with buttons where you want to map the options to particular actions.

**Comment by serge-rgb** [comment]
Added a Settings window where people can set bindings. There's no option to map drawing tablet buttons, but I think that should be mappable through driver sofware?
