### ISSUE TITLE
Closing Crash

### ISSUE THREAD

**Issue by nicstop** [serge-rgb/milton#83]
When  milton loads it looks for a "Wintab32.dll" in EasyTab_Load_Ex, if dll is missing the EasyTab is set to NULL, and when closing EasyTab_Unload will try to access the NULL pointer, which causes the crash. I guess you should do a check:

if (!EasyTab)
   {
		// Wintab32.dll not loaded.
		return;
}

**Comment by serge-rgb** [comment]
Thanks for the report. This has been reported and fixed already, but the fix is not in the latest release

**Comment by shaunidiot** [comment]
Got this problem as well. Probably related to this EasyTab issue in the milton.log file. Hope the new release is coming soon.
