### ISSUE TITLE
[MINOR BUG] Crash on exit 

### ISSUE THREAD

**Issue by MuradTroll** [serge-rgb/milton#89]
Milton.exe stops working when I try to exit (by the means of pressing the red X in the right-top corner). I am using Windows 7 64 Bit. All other functionality seems to work, and since it technically closes (just with a crash) this seems to be a minor bug, annoying but acceptable. Opening Milton again leaves the old session there (what I have drawn beforehand) so that works too.

**Comment by serge-rgb** [comment]
Known bug, and already fixed in master. Thanks for reporting :)
