### ISSUE TITLE
Set Background Color is incorrect

### ISSUE THREAD

**Issue by gingerBill** [serge-rgb/milton#9]
The colour is lighter than expected.

**Comment by serge-rgb** [comment]
Is this from the Handmade Hero episode in which Casey found the bug? 
I believe I fixed this in commit aa4970b0fa9b22fad20a271076483f6a7800e0a5, but I haven't made a new release. 
I just tried setting the background with Color Cop and I'm getting correct results. Could you please elaborate?
Thanks

**Comment by gingerBill** [comment]
I have only tried the the current release and not the latest build. I will try it later.

**Comment by serge-rgb** [comment]
I'll try to keep the master branch free of breaking changes :)

**Comment by jonathandelgado** [comment]
Thanks for the fix @serge-rgb!

**Comment by serge-rgb** [comment]
You're welcome! :) 

Apologies if you are using the master branch and your stuff starts looking weird! I will explain it more clearly in the next release but, I was trying to be "gama correct" when doing blending and I just being stupid :)
