### ISSUE TITLE
Milton doesn't not work as intented when mapping a wacom tablet to a single monitor

### ISSUE THREAD

**Issue by FredericDesgreniers** [serge-rgb/milton#94]
If I map my tablet to one of my two monitors, milton will continue to draw as if it was mapped to the two monitors. This means as I move towards the second one, milton will draw ahead of it. However the cursor is always at the right location

**Comment by serge-rgb** [comment]
I'm having trouble reproducing this issue, what version of Milton are you using?

**Comment by AsafGartner** [comment]
I'm having the same issue on version 1.5.1
![miltonmapping](https://user-images.githubusercontent.com/463270/45257380-2e768200-b3ae-11e8-9a88-5d171e2ece14.gif)

**Comment by WrGraban** [comment]
I am also having the same issue

**Comment by serge-rgb** [comment]
I'm closing this for now as I think I got it as part of some Wacom fixes. Feel free to reopen if the issue persists!
