### ISSUE TITLE
How to build Milton in MacOS?

### ISSUE THREAD

**Issue by zhengying** [serge-rgb/milton#97]
there is just a  setup_osx.sh to compile SDL lib, but how to build the whole project?  

I tried "build-lin.sh", it's not working:

-----
...
In file included from /Users/zhengying/lab/milton/src/gl.h:23:
/Users/zhengying/lab/milton/third_party/glext.h:54:9: error: 'GL_GLEXT_VERSION'
      macro redefined [-Werror,-Wmacro-redefined]
#define GL_GLEXT_VERSION 20180525
        ^
/Users/zhengying/lab/milton/third_party/SDL2-2.0.8/include/SDL_opengl_glext.h:56:9: note: 
      previous definition is here
#define GL_GLEXT_VERSION 20140521
....

Any Suggestions. thanks.

**Comment by zhengying** [comment]
MacOS now working. thanks

**Comment by serge-rgb** [comment]
Yeah I build on macos sometimes and it normally works. It's not officially supported though so I can't promise it won't break in the future :/
