### ISSUE TITLE
Milton doesn't work with Huion H640P

### ISSUE THREAD

**Issue by acbaizas** [serge-rgb/milton#99]
Hello, first off, this is a nice looking program. Pretty barebones, just the way I like it. It's like Mischief but, simpler and has layer options. Only problem is, I can't seem to use my stylus with it. If you have the time, please look into it, thank you!

**Comment by ShaunLWM** [comment]
Same as Huion H610. Is there any way I can get logs for you to view them over? Thanks!

**Comment by serge-rgb** [comment]
Should be fixed now in master. Or in the next release whenever I decide to do one :)

**Comment by kool601** [comment]
I hope you make a new release, because I'm having major issues building this on Windows. I never have luck with building things from source. :P
